name: C/C++ CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build and test
      run: |
        sudo apt-get update
        sudo apt-get install -y g++
        g++ -std=c++20 -o student_db main.cpp
        
        # Простая проверка: программа должна запуститься и завершиться
        echo "0" | timeout 5s ./student_db
        echo "✔ Базовая проверка пройдена"
        
        # Проверка тестов
        TEST_OUTPUT=$(echo -e "4\n0" | timeout 10s ./student_db 2>&1 || true)
        echo "$TEST_OUTPUT" | head -20  # Показываем первые 20 строк вывода
        
        if echo "$TEST_OUTPUT" | grep -q -i "тест"; then
          echo "✔ Тесты запущены"
        fi
