name: C/C++ CI

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y g++
    
    - name: Build
      run: make
    
    - name: Run tests
      run: |
        # Предоставляем входные данные: 4 (тесты), затем 0 (выход)
        echo -e "4\n0" | timeout 30s ./student_db | grep -q "ВСЕ.*ТЕСТОВ ПРОЙДЕНЫ УСПЕШНО"
        if [ $? -eq 0 ]; then
          echo " Все тесты прошли успешно!"
        else
          echo " Тесты не прошли"
          echo "=== Debug output ==="
          echo -e "4\n0" | timeout 10s ./student_db || true
          exit 1
        fi
