name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ libgtest-dev
        
    - name: Build main program
      run: make
      
    - name: Build tests using Makefile
      run: |
        # Если в Makefile есть цель для тестов
        make test || echo "Цель test не найдена в Makefile"
        
    - name: Run Google Tests
      run: |
        # Если tests скомпилировались через Makefile
        if [ -f "./student_tests" ]; then
          ./student_tests
        else
          # Компилируем напрямую
          g++ -std=c++20 -pthread tests.cpp -lgtest -lgtest_main -o student_tests
          ./student_tests
        fi
