name: Coverage Badge

on:
  push:
    branches: [ "main" ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ gcovr
    
    - name: Calculate coverage
      run: |
        g++ --coverage -std=c++20 -o student_db main.cpp
        
        echo -e "4\n0" | ./student_db
        
        gcovr --print-summary | grep "lines:" | awk '{print $2}' | tr -d '%' > coverage.txt
    
    - name: Create badge
      run: |
        COVERAGE=$(cat coverage.txt)
        echo "![Coverage](https://img.shields.io/badge/Coverage-${COVERAGE}%25-brightgreen)" > COVERAGE.md
    
    - name: Commit badge reference
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add COVERAGE.md
        git commit -m "Add coverage badge reference" || exit 0
        git push
